#!/usr/bin/env bash

ba_kit_message() {
  local key="$1"
  shift || true
  case "${BA_KIT_INTERACTION_LANGUAGE:-vi}:${key}" in
    en:commands) printf 'Commands:' ;;
    en:supported_runtimes) printf 'Supported runtimes:' ;;
    en:products) printf 'Products:' ;;
    en:framework_missing) printf 'BA-kit CLI — framework is not installed. Run: bakit install' ;;
    en:free_product) printf '  %s — Free (no sign-in required)' "$1" ;;
    en:private_product) printf '  %s — Purchase + gh auth login required: %s' "$1" "$2" ;;
    en:install_usage) printf 'Usage: bakit install [--version v2.0.0] [--runtime claude,codex,agy]' ;;
    en:uninstall_usage) printf 'Usage: bakit uninstall [--runtime claude,codex,agy]' ;;
    en:unknown_argument) printf 'Unknown argument: %s' "$1" ;;
    en:install_title) printf '  BA-KIT INSTALL' ;;
    en:update_title) printf '  BA-KIT UPDATE' ;;
    en:doctor_title) printf '  BA-kit HEALTH CHECK' ;;
    en:uninstall_title) printf '  UNINSTALL' ;;
    en:detect_product) printf '  Detected: %s' "$1" ;;
    en:private_hidden) printf "  (private products require 'gh auth login' to appear)" ;;
    en:multiple_products) printf 'You can access multiple BA-kit products:' ;;
    en:choose_product) printf 'Choose a product to install (1-%s): ' "$1" ;;
    en:invalid_choice) printf 'Invalid selection.' ;;
    en:selected_product) printf '  Selected: %s' "$1" ;;
    en:find_latest) printf 'Checking the latest version...' ;;
    en:selected_version) printf '  Version: %s' "$1" ;;
    en:release_changes) printf 'Changes in this release:' ;;
    en:download_release) printf 'Downloading %s %s...' "$1" "$2" ;;
    en:download_done) printf '  Download complete. Verifying checksum...' ;;
    en:checksum_valid) printf '  Checksum valid.' ;;
    en:inspect_archive) printf 'Inspecting archive...' ;;
    en:archive_valid) printf '  Archive valid.' ;;
    en:extract_archive) printf 'Extracting archive...' ;;
    en:extract_done) printf '  Extraction complete.' ;;
    en:install_files) printf 'Installing files...' ;;
    en:update_files) printf 'Updating files...' ;;
    en:no_runtime_work) printf 'No runtime needs installation or update.' ;;
    en:install_success) printf '  INSTALLATION SUCCESSFUL!' ;;
    en:product_label) printf '  Product:    %s' "$1" ;;
    en:version_label) printf '  Version:    %s' "$1" ;;
    en:no_agents_hooks) printf '  No agents, hooks, or scripts.' ;;
    en:get_started) printf '  Get started:' ;;
    en:get_started_runtime) printf '    Open Claude Code, Codex, or AGY' ;;
    en:get_started_command) printf '    Enter /ba-start to begin a BA project' ;;
    en:update_later) printf '  Update later:' ;;
    en:not_installed) printf 'BA-kit is not installed.' ;;
    en:run_install) printf 'Run: bakit install' ;;
    en:product_group) printf 'Product: %s (%s)' "$1" "$2" ;;
    en:latest_version) printf 'Latest version: %s' "$1" ;;
    en:already_latest) printf 'Already using the latest version.' ;;
    en:update_confirm) printf 'Update to %s? (Y/n): ' "$1" ;;
    en:cancelled_group) printf 'Cancelled %s.' "$1" ;;
    en:uninstalled_status) printf '[UNINSTALLED] %s: %s %s (%s preserved files)' "$1" "$2" "$3" "$4" ;;
    en:not_installed_status) printf '[NOT INSTALLED] %s: not installed' "$1" ;;
    en:recovery_status) printf '[RECOVERY REQUIRED] %s: the previous transaction was not fully recovered' "$1" ;;
    en:github_signed_in) printf '[OK]   GitHub CLI: signed in (for private products)' ;;
    en:github_signed_out) printf '[OK]   GitHub CLI: not signed in (Solo Basic remains available)' ;;
    en:access_title) printf 'Access:' ;;
    en:access_free) printf '  [OK]   %s — free, always available' "$1" ;;
    en:access_granted) printf '  [OK]   %s — access granted' "$1" ;;
    en:access_missing) printf '  [MISSING] %s — access not granted' "$1" ;;
    en:access_login) printf '  [MISSING] %s — requires gh auth login' "$1" ;;
    en:components_title) printf 'Installed components:' ;;
    en:version_uninstalled) printf '  %s: %s: uninstalled (%s preserved files)' "$1" "$2" "$3" ;;
    en:version_missing) printf '  %s: (not installed)' "$1" ;;
    en:no_installed_runtime) printf 'No installed runtime found.' ;;
    en:uninstall_list) printf 'The following runtimes will be removed (with backup first):' ;;
    en:uninstall_confirm) printf 'Continue? (y/N): ' ;;
    en:cancelled) printf 'Cancelled.' ;;
    en:uninstall_done) printf 'Selected runtimes were removed using schema-v3 transaction.' ;;
    en:runtime_empty) printf 'Error: --runtime contains an empty value.' ;;
    en:runtime_valid) printf 'Valid runtimes: %s' "$1" ;;
    en:runtime_invalid) printf "Error: runtime '%s' is invalid." "$1" ;;
    en:auto_install_available) printf '%s can be installed automatically with:' "$1" ;;
    en:install_now) printf 'Install now? (y/N): ' ;;
    en:installing_dependency) printf 'Installing %s...' "$1" ;;
    en:dependency_success) printf '  %s installed successfully.' "$1" ;;
    en:dependency_failed) printf '  Failed to install %s.' "$1" ;;
    en:install_instructions) printf 'Installation instructions:' ;;
    en:private_requires_gh) printf '%s is private and requires GitHub CLI for authentication.' "$1" ;;
    en:private_requires_login) printf '%s is private and requires GitHub sign-in.' "$1" ;;
    en:run_following) printf 'Run the following command and follow its instructions:' ;;
    en:after_install_gh) printf 'After installation, run: gh auth login' ;;
    en:no_product_access) printf 'You do not have access to any BA-kit product.' ;;
    en:free_product_error) printf 'BA-kit Solo Basic is free — please report this error.' ;;
    en:paid_products) printf 'Paid products:' ;;
    en:public_release_error) printf 'Error: Could not retrieve the public release for %s. Check the network and try again.' "$1" ;;
    en:private_release_error) printf 'Error: Could not retrieve a release for %s.' "$1" ;;
    en:product_conflict) printf '  PRODUCT CONFLICT DETECTED (%s)' "$1" ;;
    en:installed_product) printf 'Installed locally: %s' "$1" ;;
    en:requested_product) printf 'Requested product: %s' "$1" ;;
    en:cannot_overwrite) printf 'A different product cannot be overwritten. Uninstall %s first:' "$1" ;;
    en:then_rerun) printf 'Then run again:' ;;
    en:already_installed_skip) printf '%s: %s %s is already installed; skipping.' "$1" "$2" "$3" ;;
    en:already_installed) printf '%s %s is already installed.' "$1" "$2" ;;
    en:reinstall_confirm) printf 'Reinstall it? (y/N): ' ;;
    en:reinstalling) printf 'Reinstalling %s...' "$1" ;;
    en:asset_missing) printf 'Error: asset %s was not found in release %s.' "$1" "$2" ;;
    en:checksum_required) printf 'Error: release %s has no required checksum; no files were installed.' "$1" ;;
    en:download_error) printf 'Error: Could not download %s %s.' "$1" "$2" ;;
    en:check_network) printf 'Check the network connection and try again.' ;;
    en:checksum_download_error) printf 'Error: Could not download the checksum.' ;;
    en:checksum_mismatch) printf 'Error: Downloaded file checksum does not match.' ;;
    en:checksum_skipped) printf '  Checksum file not found; verification skipped.' ;;
    en:backup_start) printf 'Backing up the current %s to:' "$1" ;;
    en:backup_done) printf '  Backup complete.' ;;
    en:backup_cleaned) printf '  Removed %s old backups (kept the latest %s).' "$1" "$2" ;;
    en:archive_invalid) printf 'Error: Invalid archive: %s' "$1" ;;
    en:extract_failed) printf 'Error: Could not extract the archive.' ;;
    en:file_counts) printf '  %s new | %s updated | %s preserved' "$1" "$2" "$3" ;;
    en:finalizing) printf 'Finalizing installation...' ;;
    en:complete) printf '  Complete.' ;;
    en:health_check) printf '  Health check:' ;;
    en:solo_structure_error) printf 'Error: Invalid Solo archive structure. Expected: %s; actual: %s' "$1" "$2" ;;
    en:solo_claude_error) printf 'Error: .claude/ in the Solo archive may contain only skills/ and templates/.' ;;
    en:solo_core_error) printf 'Error: ba-kit/ in the Solo archive may contain only core/.' ;;
    en:solo_skills_error) printf 'Error: Invalid skill set. Expected: %s; actual: %s' "$1" "$2" ;;
    en:product_overwrite_error) printf 'Error: %s cannot overwrite %s.' "$1" "$2" ;;
    en:uninstall_first) printf 'Uninstall %s first: bakit uninstall --runtime %s' "$1" "$2" ;;
    en:transaction_rollback) printf 'Error: installation failed; restoring changed runtimes...' ;;
    en:manual_recovery) printf 'Error: a runtime requires manual recovery; run bakit doctor.' ;;
    en:state_recovery) printf 'Error: %s requires recovery. Run bakit doctor for instructions.' "$1" ;;
    en:state_invalid) printf 'Error: invalid schema-v3 state at %s. Run bakit doctor.' "$1" ;;
    en:cli_upgrade) printf 'Error: %s requires CLI >= 2.0.0 to continue.' "$1" ;;
    en:state_incomplete) printf 'Error: incomplete BA-kit state at %s. No files were changed.' "$1" ;;
    en:unsupported_product) printf "Error: product '%s' is not supported at %s." "$1" "$2" ;;
    en:updating_groups) printf 'Updating %s product groups...' "$1" ;;
    en:unsupported_product_id) printf "Error: Product '%s' is not supported." "$1" ;;
    en:access_revoked) printf 'Access to %s has been revoked.' "$1" ;;
    en:latest_check_error) printf 'Error: Could not check the latest version.' ;;
    vi:commands) printf 'Lệnh:' ;;
    vi:supported_runtimes) printf 'Runtime hỗ trợ:' ;;
    vi:products) printf 'Sản phẩm:' ;;
    vi:framework_missing) printf 'BA-kit CLI — chưa cài framework. Chạy: bakit install' ;;
    vi:free_product) printf '  %s — Miễn phí (không cần đăng nhập)' "$1" ;;
    vi:private_product) printf '  %s — Cần mua + gh auth login: %s' "$1" "$2" ;;
    vi:install_usage) printf 'Dùng: bakit install [--version v2.0.0] [--runtime claude,codex,agy]' ;;
    vi:uninstall_usage) printf 'Dùng: bakit uninstall [--runtime claude,codex,agy]' ;;
    vi:unknown_argument) printf 'Không hiểu tham số: %s' "$1" ;;
    vi:install_title) printf '  BA-KIT INSTALL' ;;
    vi:update_title) printf '  BA-KIT UPDATE' ;;
    vi:doctor_title) printf '  BA-kit HEALTH CHECK' ;;
    vi:uninstall_title) printf '  GỠ CÀI ĐẶT' ;;
    vi:detect_product) printf '  Phát hiện: %s' "$1" ;;
    vi:private_hidden) printf "  (sản phẩm riêng tư cần 'gh auth login' để hiển thị)" ;;
    vi:multiple_products) printf 'Bạn có quyền truy cập nhiều sản phẩm BA-kit:' ;;
    vi:choose_product) printf 'Chọn sản phẩm muốn cài (1-%s): ' "$1" ;;
    vi:invalid_choice) printf 'Lựa chọn không hợp lệ.' ;;
    vi:selected_product) printf '  Đã chọn: %s' "$1" ;;
    vi:find_latest) printf 'Đang tìm phiên bản mới nhất...' ;;
    vi:selected_version) printf '  Phiên bản: %s' "$1" ;;
    vi:release_changes) printf 'Thay đổi trong phiên bản này:' ;;
    vi:download_release) printf 'Đang tải %s %s...' "$1" "$2" ;;
    vi:download_done) printf '  Đã tải xong. Đang kiểm tra checksum...' ;;
    vi:checksum_valid) printf '  Checksum hợp lệ.' ;;
    vi:inspect_archive) printf 'Đang kiểm tra archive...' ;;
    vi:archive_valid) printf '  Archive hợp lệ.' ;;
    vi:extract_archive) printf 'Đang giải nén...' ;;
    vi:extract_done) printf '  Giải nén hoàn tất.' ;;
    vi:install_files) printf 'Đang cài đặt files...' ;;
    vi:update_files) printf 'Đang cập nhật files...' ;;
    vi:no_runtime_work) printf 'Không có runtime nào cần cài/cập nhật.' ;;
    vi:install_success) printf '  CÀI ĐẶT THÀNH CÔNG!' ;;
    vi:product_label) printf '  Sản phẩm:   %s' "$1" ;;
    vi:version_label) printf '  Phiên bản:  %s' "$1" ;;
    vi:no_agents_hooks) printf '  Không có agents, hooks, hay scripts.' ;;
    vi:get_started) printf '  Bắt đầu sử dụng:' ;;
    vi:get_started_runtime) printf '    Vào Claude Code, Codex hoặc AGY' ;;
    vi:get_started_command) printf '    Gõ /ba-start để bắt đầu dự án BA' ;;
    vi:update_later) printf '  Cập nhật sau này:' ;;
    vi:not_installed) printf 'BA-kit chưa được cài đặt.' ;;
    vi:run_install) printf 'Chạy: bakit install' ;;
    vi:product_group) printf 'Sản phẩm: %s (%s)' "$1" "$2" ;;
    vi:latest_version) printf 'Phiên bản mới nhất: %s' "$1" ;;
    vi:already_latest) printf 'Đang dùng phiên bản mới nhất.' ;;
    vi:update_confirm) printf 'Cập nhật lên %s? (Y/n): ' "$1" ;;
    vi:cancelled_group) printf 'Đã hủy nhóm %s.' "$1" ;;
    vi:uninstalled_status) printf '[ĐÃ GỠ] %s: %s %s (còn %s file được giữ lại)' "$1" "$2" "$3" "$4" ;;
    vi:not_installed_status) printf '[CHƯA] %s: chưa cài đặt' "$1" ;;
    vi:recovery_status) printf '[CẦN KHÔI PHỤC] %s: giao dịch trước đó chưa được khôi phục hoàn toàn' "$1" ;;
    vi:github_signed_in) printf '[OK]   GitHub CLI: đã đăng nhập (cho sản phẩm riêng tư)' ;;
    vi:github_signed_out) printf '[OK]   GitHub CLI: chưa đăng nhập (Solo Basic vẫn dùng được)' ;;
    vi:access_title) printf 'Quyền truy cập:' ;;
    vi:access_free) printf '  [OK]   %s — miễn phí, luôn có sẵn' "$1" ;;
    vi:access_granted) printf '  [OK]   %s — có quyền truy cập' "$1" ;;
    vi:access_missing) printf '  [THIẾU] %s — chưa có quyền' "$1" ;;
    vi:access_login) printf '  [THIẾU] %s — cần gh auth login' "$1" ;;
    vi:components_title) printf 'Components đã cài:' ;;
    vi:version_uninstalled) printf '  %s: %s: đã gỡ (còn %s file được giữ lại)' "$1" "$2" "$3" ;;
    vi:version_missing) printf '  %s: (chưa cài)' "$1" ;;
    vi:no_installed_runtime) printf 'Không có runtime nào đã cài.' ;;
    vi:uninstall_list) printf 'Sẽ gỡ các runtime sau (có backup trước khi xóa):' ;;
    vi:uninstall_confirm) printf 'Bạn có chắc muốn tiếp tục? (y/N): ' ;;
    vi:cancelled) printf 'Đã hủy.' ;;
    vi:uninstall_done) printf 'Đã gỡ các runtime được chọn bằng transaction schema-v3.' ;;
    vi:runtime_empty) printf 'Lỗi: --runtime chứa giá trị rỗng.' ;;
    vi:runtime_valid) printf 'Runtime hợp lệ: %s' "$1" ;;
    vi:runtime_invalid) printf "Lỗi: runtime '%s' không hợp lệ." "$1" ;;
    vi:auto_install_available) printf 'Phát hiện có thể tự động cài %s bằng lệnh:' "$1" ;;
    vi:install_now) printf 'Cài ngay? (y/N): ' ;;
    vi:installing_dependency) printf 'Đang cài %s...' "$1" ;;
    vi:dependency_success) printf '  Cài %s thành công.' "$1" ;;
    vi:dependency_failed) printf '  Cài %s thất bại.' "$1" ;;
    vi:install_instructions) printf 'Cách cài:' ;;
    vi:private_requires_gh) printf '%s là sản phẩm riêng tư, cần GitHub CLI để xác thực.' "$1" ;;
    vi:private_requires_login) printf '%s là sản phẩm riêng tư, cần đăng nhập GitHub.' "$1" ;;
    vi:run_following) printf 'Chạy lệnh sau và làm theo hướng dẫn:' ;;
    vi:after_install_gh) printf 'Sau khi cài, chạy: gh auth login' ;;
    vi:no_product_access) printf 'Bạn chưa có quyền truy cập bất kỳ sản phẩm BA-kit nào.' ;;
    vi:free_product_error) printf 'BA-kit Solo Basic là sản phẩm miễn phí — vui lòng báo lỗi này.' ;;
    vi:paid_products) printf 'Các sản phẩm trả phí:' ;;
    vi:public_release_error) printf 'Lỗi: Không thể lấy release công khai của %s. Kiểm tra mạng và thử lại.' "$1" ;;
    vi:private_release_error) printf 'Lỗi: Không thể lấy release của %s.' "$1" ;;
    vi:product_conflict) printf '  PHÁT HIỆN XUNG ĐỘT SẢN PHẨM (%s)' "$1" ;;
    vi:installed_product) printf 'Local đang cài: %s' "$1" ;;
    vi:requested_product) printf 'Bạn muốn cài:   %s' "$1" ;;
    vi:cannot_overwrite) printf 'Không thể cài đè sản phẩm khác. Bạn cần gỡ %s trước:' "$1" ;;
    vi:then_rerun) printf 'Sau đó chạy lại:' ;;
    vi:already_installed_skip) printf '%s: %s %s đã được cài đặt, bỏ qua.' "$1" "$2" "$3" ;;
    vi:already_installed) printf '%s %s đã được cài đặt.' "$1" "$2" ;;
    vi:reinstall_confirm) printf 'Bạn có muốn cài lại không? (y/N): ' ;;
    vi:reinstalling) printf 'Đang cài lại %s...' "$1" ;;
    vi:asset_missing) printf 'Lỗi: Không tìm thấy asset %s trong release %s.' "$1" "$2" ;;
    vi:checksum_required) printf 'Lỗi: Release %s thiếu checksum bắt buộc; chưa cài file nào.' "$1" ;;
    vi:download_error) printf 'Lỗi: Không thể tải %s %s.' "$1" "$2" ;;
    vi:check_network) printf 'Vui lòng kiểm tra kết nối mạng và thử lại.' ;;
    vi:checksum_download_error) printf 'Lỗi: Không thể tải checksum.' ;;
    vi:checksum_mismatch) printf 'Lỗi: File tải về bị lỗi (checksum không khớp).' ;;
    vi:checksum_skipped) printf '  Không tìm thấy file checksum, bỏ qua bước kiểm tra.' ;;
    vi:backup_start) printf 'Đang backup %s hiện tại vào:' "$1" ;;
    vi:backup_done) printf '  Backup hoàn tất.' ;;
    vi:backup_cleaned) printf '  Đã dọn %s backup cũ (giữ %s gần nhất).' "$1" "$2" ;;
    vi:archive_invalid) printf 'Lỗi: Archive không hợp lệ: %s' "$1" ;;
    vi:extract_failed) printf 'Lỗi: Không thể giải nén archive.' ;;
    vi:file_counts) printf '  %s file mới | %s file cập nhật | %s file giữ nguyên' "$1" "$2" "$3" ;;
    vi:finalizing) printf 'Đang hoàn tất cài đặt...' ;;
    vi:complete) printf '  Hoàn tất.' ;;
    vi:health_check) printf '  Kiểm tra sức khỏe:' ;;
    vi:solo_structure_error) printf 'Lỗi: Cấu trúc archive Solo không đúng. Mong đợi: %s, thực tế: %s' "$1" "$2" ;;
    vi:solo_claude_error) printf 'Lỗi: .claude/ trong archive Solo phải chỉ có skills/ và templates/' ;;
    vi:solo_core_error) printf 'Lỗi: ba-kit/ trong archive Solo phải chỉ có core/' ;;
    vi:solo_skills_error) printf 'Lỗi: Skill set không đúng. Mong đợi: %s, thực tế: %s' "$1" "$2" ;;
    vi:product_overwrite_error) printf 'Lỗi: %s không thể cài đè lên %s.' "$1" "$2" ;;
    vi:uninstall_first) printf 'Gỡ %s trước: bakit uninstall --runtime %s' "$1" "$2" ;;
    vi:transaction_rollback) printf 'Lỗi: cài đặt thất bại, đang khôi phục các runtime đã thay đổi...' ;;
    vi:manual_recovery) printf 'Lỗi: một runtime cần khôi phục thủ công; chạy bakit doctor.' ;;
    vi:state_recovery) printf 'Lỗi: trạng thái cần khôi phục tại %s. Chạy bakit doctor để xem hướng dẫn.' "$1" ;;
    vi:state_invalid) printf 'Lỗi: schema-v3 không hợp lệ tại %s. Chạy bakit doctor.' "$1" ;;
    vi:cli_upgrade) printf 'Lỗi: %s cần CLI >= 2.0.0 để tiếp tục.' "$1" ;;
    vi:state_incomplete) printf 'Lỗi: trạng thái BA-kit chưa đầy đủ tại %s. Không có file nào được thay đổi.' "$1" ;;
    vi:unsupported_product) printf "Lỗi: sản phẩm '%s' không được hỗ trợ tại %s." "$1" "$2" ;;
    vi:updating_groups) printf 'Đang cập nhật %s nhóm sản phẩm...' "$1" ;;
    vi:unsupported_product_id) printf "Lỗi: Sản phẩm '%s' không được hỗ trợ." "$1" ;;
    vi:access_revoked) printf 'Quyền truy cập %s đã bị thu hồi.' "$1" ;;
    vi:latest_check_error) printf 'Lỗi: Không thể kiểm tra phiên bản mới.' ;;
    *) printf '%s' "$key" ;;
  esac
}

ba_kit_say() {
  ba_kit_message "$@"
  printf '\n'
}
